### PR TITLE
fix after netflix changes

### PR DESCRIPTION
**Pull request by redledyba**
apparently n.nodeValue is always null now, so I changed to innerText

### CODE REVIEW

**Comment by 71** [comment]
Are you using Chrome or Firefox? On Chrome 111.0.5563, `nodeValue` still works, and `innerText` does not. Or maybe we're being served different versions of the Netflix player.

**Comment by redledyba** [comment]
That's interesting. I'm using Firefox, never tested on Chrome. It used to work fine on Firefox until a couple of months ago. Maybe it stopped working after a Firefox update, but I have no idea which update that was. I also tested on Waterfox latest version and got the same behavior that on Firefox.

**Comment by 71** [comment]
Mhm, okay, I'll try it in Firefox as well. I have an idea for something that might work both in Firefox and Chrome (using a `TreeWalker` to iterate over all text nodes in the container, instead of a simple loop over child elements), but I won't be able to test it today.

**Comment by 71** [comment]
Indeed, Firefox worked as you explained. Latest master should work on both Firefox and Chrome!

**Pull request closed without merging**
